{{- $secret := lookup "v1" "Secret" $.Release.Namespace $.Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- if $secret }}
  root-password: {{ index $secret.data "root-password" | b64dec | quote }}
  {{- else }}
  root-password: {{ derivePassword 0 "maximum" ( randAscii 20 ) $.Chart.Name $.Chart.Home | quote }}
  {{- end }}
  root-user: {{ $.Values.postgresql.auth.username }}
type: Opaque
