---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    kind: Deployment
    {{- include "selectorLabels" $ | nindent 4 }}
